[package]
name = "waypoint_navigation"
version = "0.0.0"
edition = "2021"

[profile.colcon]
inherits = "release"

[dependencies]
r2r = "0.7.0"
futures = "0.3.15"
tokio = { version = "1", features = ["full"] }
