waypoints:
  - id: 1
    position:
      x: 1.0
      y: -0.5
    euler_angle:
      z: 0.1
  - id: 2
    position:
      x: 0.541
      y: 0.555
    euler_angle:
      z: -0.333
  - id: 3
    position:
      x: -1.958
      y: -0.471
    euler_angle:
      z: 0.020