name: build-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: osrf/ros:humble-desktop
    strategy:
      matrix:
        rosdistro:
          - humble

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Apt update
        run: |
          sudo apt update -y

      - name : ROS 2 Rust install 
        run: ./.github/workflows/ros2_rust_install_script.sh

      - name: Build Test
        run: |
          mkdir ../catkin_ws/src -p
          cp -r ./* ../catkin_ws/src
          cd ../catkin_ws
          rosdep update
          rosdep install -r -y --from-paths --ignore-src ./
          source /opt/ros/humble/setup.bash
          source $HOME/.cargo/env
          colcon  build --symlink-install
        shell: bash